# Generated by Django 5.0.2 on 2024-03-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active_user_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'user')], default=2),
        ),
    ]
